name: "Terraform (dev)"

on:
  pull_request:
    branches:
      - main
    paths:
      - "envs/dev/**"
      - "module/**"
      - "!*.md"

  issue_comment:
    types: [created]

jobs:
  terraform:
    uses: ./.github/workflows/reusable-job-terraform.yaml
    with:
      env: "dev"
      working_dir: "envs/dev"
      aws_role_arn: "arn:aws:iam::12345678910:role/my-cicd-role-dev"
      aws_region: "ap-northeast-1"
      is_apply: ${{ github.event_name == 'issue_comment' && github.event.comment.body == '/terraform apply' }}
    secrets: inherit
    permissions:
      id-token: write
      contents: read
      actions: read
      pull-requests: write
